apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  # storageaccount: pd-standard
  storageaccount: pd-ssd
  fsType: xfs
allowVolumeExpansion: true